<a href="https://colab.research.google.com/github/AleximperV/ThucHanhDeepLearning/blob/main/numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy as np


ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as


In [ ]:
import numpy as np

# Cách 1
# Tạo list
my_list = [1,9,15,39]
print('Python list:', my_list)
# Chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# Cách 2
a = np.array([1,9,15,39])
print(a)

Python list: [1, 9, 15, 39]


NameError: name 'np' is not defined

In [ ]:
import numpy as np

In [ ]:
tensorflow_basic

In [ ]:


# Cách 1
# Tạo list
my_list = [1,9,15,39]
print('Python list:', my_list)
# Chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# Cách 2
a = np.array([1,9,15,39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
d = np.array([
    [[1.,2.,3.],[4.,5.,6.]],
    [[7.,8.,9.], [10,11,12]]
    ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
# Tạo array với giá trị ban đầu là 0 hoặc 1
e = np.zeros((2,2))
f = np.ones((3,3))
print('Zero matrix: \n',e)
print('One matrix: \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print (e)
print (e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]
              ])
print(g)
print(g.shape)
h = g.reshape(3,4)
print('reshape (3,4)\n', h)
j = g.reshape(3,2,2)
print('reshape (3,2,2)\n', j)
k = g.reshape(2,3,2)
print('reshape (2,3,2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [ ]:
# Platten là chuyển array nhiều chiều về 1 chiều
e = np.array([[1.,2.,3.],[4.,5.,6.]])

f = e.flatten()
print(f)
g = np.array([[[1.,2.,3.], [4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]
              ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
# Thêm dòng dữ liệu với hstack và vstack
# Hàm hstack((x, y)) cho phép thêm nối thêm dữ liệu ma trận y vào sau ma trận x (chiều ngang).
# Hàm vstack((x, y)) cho phép thêm nối thêm dữ liệu ma trận y vào dưới ma trận x (chiều dọc).
f = np.array([1.,2.,3.])
g = np.array([4.,5.,6.])
h_stack = np.hstack((f,g))
print('Nối ma trận theo chiều ngang\n',h_stack)
v_stack = np.vstack((f,g))
print('Nối ma trận theo chiều dọc\n', v_stack)

Nối ma trận theo chiều ngang
 [1. 2. 3. 4. 5. 6.]
Nối ma trận theo chiều dọc
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(100, size=(5,))
print('random 1-D array \n', a)
b = np.random.randint(100, size=(3,4))
print('random 2-D array \n', b)
c = np.random.randint(100, size=(3,4,3 ))
print('random 3-D array \n', c)

random 1-D array 
 [84 60 63 93 19]
random 2-D array 
 [[20 22 79 77]
 [88 45 92 97]
 [66 20 98 61]]
random 3-D array 
 [[[81 39  1]
  [84 23 63]
  [66 32 85]
  [95 17 26]]

 [[22 47  4]
  [50 33 93]
  [48 26  9]
  [11 90 29]]

 [[56 60 63]
  [56 66 73]
  [53 11  1]
  [52 11 74]]]


In [ ]:
# Sinh mảng số thực trong khoảng [0, 1]
a = np.random.rand(5)
print('random 1-D array \n', a)
b = np.random.rand(3,4)
print('random 2-D array \n', b)
c = np.random.rand(3,4,3 )
print('random 3-D array \n', c)

random 1-D array 
 [0.67164964 0.47620182 0.87150256 0.48088455 0.1943798 ]
random 2-D array 
 [[0.6727105  0.32808753 0.04931318 0.71200752]
 [0.62603752 0.70024637 0.79827828 0.89197127]
 [0.38725699 0.47667395 0.77499306 0.2979557 ]]
random 3-D array 
 [[[0.84235553 0.41585777 0.85006483]
  [0.83991869 0.94523078 0.74667858]
  [0.16977631 0.18763912 0.35927608]
  [0.48391696 0.50811714 0.88971736]]

 [[0.38139588 0.0348788  0.86862057]
  [0.23993678 0.85829057 0.55532919]
  [0.18523981 0.89487234 0.75736758]
  [0.05441746 0.53171332 0.00719876]]

 [[0.75045296 0.88520273 0.53347882]
  [0.05764407 0.01197518 0.55910681]
  [0.11588869 0.82783075 0.08575793]
  [0.62694668 0.12305555 0.50771721]]]


In [ ]:
# Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
# Hàm: Numpy.random.normal(loc, scale, size)
# Loc: giá trị trung tâm - Scale: độ lệch chuẩn - Size: số phần tử trả về
a = np.random.normal(7,0.5,10)
print(a)

[6.32924253 6.64503389 6.78303733 6.98567925 6.84523367 7.50411479
 7.46221591 6.83451459 7.29632477 6.61322533]


In [ ]:
# Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước
a = np.random.choice([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(a)
# Sinh ngẫu nhiên một ma trận 3 x 5 từ mảng giá trị cho trước
b = np.random.choice([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], size=(3,5))
print(b)

15
[[ 7  3 13  9 12]
 [11  5  1 11  5]
 [ 8 12 11  1 15]]


In [ ]:
# Bài 1: Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
# chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)
mang_ngau_nhien = np.random.randint(0, 21, size=(3, 3))
print('Mảng ngẫu nhiên: \n',mang_ngau_nhien)
kiem_tra_so_0 = np.all(mang_ngau_nhien != 0)
print('Các phần tử trong mảng khác 0: ',kiem_tra_so_0)

Mảng ngẫu nhiên: 
 [[ 5  3  3]
 [16 14 19]
 [11  8 13]]
Các phần tử trong mảng khác 0:  True


In [ ]:
# Bài 2: Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
# chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)
mang_ngau_nhien = np.random.randint(0, 21, size=(3, 3))
print('Mảng ngẫu nhiên: \n',mang_ngau_nhien)
kiem_tra_so_0 = np.any(mang_ngau_nhien != 0)
print('Tồn tại một phần tử khác 0: ',kiem_tra_so_0)

Mảng ngẫu nhiên: 
 [[ 0 13 16]
 [11 11 18]
 [ 3 18 12]]
Tồn tại một phần tử khác 0:  True


In [ ]:
# Bài 3: Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
# numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.
arr1_1 = np.random.randint(100, size=(8,))
arr1_2 = np.random.randint(100, size=(8,))

print('So sánh ngẫu nhiên: \n')
print('Mảng ngẫu nhiên 1: ', arr1_1)
print('Mảng ngẫu nhiên 2: ', arr1_2)

greater_compare_1 = np.greater(arr1_1,arr1_2)
print('So sánh: arr1_1 > arr1_2: ', greater_compare_1)

greater_equal_compare_1 = np.greater_equal(arr1_1,arr1_2)
print('So sánh: arr1_1 >= arr1_2: ', greater_equal_compare_1)

less_compare_1 = np.less(arr1_1,arr1_2)
print('So sánh: arr1_1 < arr1: ', less_compare_1)

less_equal_compare_1 = np.less_equal(arr1_1,arr1_2)
print('So sánh: arr1_1 <= arr1_2: ', less_equal_compare_1)

So sánh ngẫu nhiên: 

Mảng ngẫu nhiên 1:  [36 20 89 44 68 46 90 81]
Mảng ngẫu nhiên 2:  [98  8 90 70 59 60 54 53]
So sánh: arr1_1 > arr1_2:  [False  True False False  True False  True  True]
So sánh: arr1_1 >= arr1_2:  [False  True False False  True False  True  True]
So sánh: arr1_1 < arr1:  [ True False  True  True False  True False False]
So sánh: arr1_1 <= arr1_2:  [ True False  True  True False  True False False]


In [ ]:
# Bài 4: Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
mang_1 = np.ones(10)
mang_2 = np.zeros(10)
mang_3 = np.full(10,5)
mang = np.concatenate((mang_1,mang_2,mang_3))
print(mang)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [ ]:
# Bài 5: Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]
mang_so_nguyen_chan = np.arange(30,71,2)
# Chạy từ số 30 và kết thúc ở 71 (Tối đa 70) với bước nhảy là 2
print(mang_so_nguyen_chan)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
# Bài 6: Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
# (Tìm hiểu hàm identity của numpy)
# np.identity sẽ luôn tạo ma trận vuông, với đường chéo chính (Trái Cao xuống Phải Dưới) luôn là 1
# và các phần tử còn lại là 0
ma_tran_don_vi = np.identity(3)
print(ma_tran_don_vi)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Bài 7: Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử
# đầu và cuối
mang_ngau_nhien_bai_7 = np.random.randint(15,56, size=(10,))
print(mang_ngau_nhien_bai_7)
# Cắt bắt đầu phần tử thứ 2 (index 0 đến index 1) và ngừng ở phần tử cuối cùng là -1
# nghĩa là phần tử -1 loại ra, kết thúc ở phần tử kế cuối
mang_cat= mang_ngau_nhien_bai_7[1:-1]
print(mang_cat)

[45 32 22 35 23 43 49 55 15 50]
[32 22 35 23 43 49 55 15]
